### ISSUE TITLE
Use own images set to create voxelized shape

### ISSUE THREAD

**Issue by BLCKPSTV** [chrischoy/3D-R2N2#21]
How can I use a set of own images to create a new (no example based) voxel shape.

I want to use pots (images I have from them to make a 3D voxel shape)

The instruction show only the learning aspect and not how to use the code on new images. Or I'm not fully understanding the shapenet part.

**Comment by Metal-joker** [comment]
same issue

**Comment by BLCKPSTV** [comment]
Anything changed? Anybody an idea to train own images??

**Comment by Metal-joker** [comment]
Still no solution

**Comment by heromanba** [comment]
The images of training dataset have a shape of (127, 127, 3). So you need to resize your image to this shape so that the network can test the output using you image.

**Comment by kitachan** [comment]
Convert your images to size 127 x 127.

**Comment by ramyagopinathpsg** [comment]
I converted the image size to 127 x 127 but still its not working

**Comment by ramyagopinathpsg** [comment]
> Convert your images to size 127 x 127.

its not working when i changed the image size to 127 x 127

**Comment by haohoaz** [comment]
the same issue 
How should I run it with the pictures I took

**Comment by haohoaz** [comment]
> 



> 如何使用一组自己的图像来创建新的（不基于示例的）体素形状。
> 
> 我想使用花盆（我从中得到的图像来制作 3D 体素形状）
> 
> 该说明仅显示学习方面，而不显示如何在新图像上使用代码。或者我没有完全理解形状网部分。
> 
> 更新
> 
> 稍微更改了 demo.py 代码，并在imgs目录中放置了一些图片。
> 
> 当运行python demo.py newobject.obj时
> 
> 我收到此错误。
> 
> ```
> Traceback (most recent call last):
>   File "demo.py", line 84, in <module>
>     main()
>   File "demo.py", line 52, in main
>     demo_imgs = load_demo_images()
>   File "demo.py", line 43, in load_demo_images
>     return np.array(ims)
> ValueError: could not broadcast input array from shape (3,300,300) into shape (3)
> ```
> 
> 我不知道这意味着什么。
> 
> 尝试将图像大小调整为较小的宽度和长度，但这仍然给我同样的错误。

Hi, please did you fix this now, I really don't know how to change it

**Comment by leezanla** [comment]
It seems that the input channel of this model can only be three channels, you need to convert to three channels in RGB format
这个模型输入的通道好像只能是三通道，你需要转为RGB格式的三通道
