### ISSUE TITLE
ValueError: You are tring to use the old GPU back-end. 

### ISSUE THREAD

**Issue by speed8928** [chrischoy/3D-R2N2#22]
Hi I use windows 10 to implement the project and it turns out the error below:
ValueError: You are tring to use the old GPU back-end. It was removed from Theano. Use device=cuda*

I tried to follow your link that from error
https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29 
and install theano pygpu, but nothing good come out.

I also tried change the Theano variable device = gpu to device = cuda0 and it gives me the error below:

(py3) C:\Users\speed\source\3D-R2N2>python demo.py prediction.obj
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType
Downloading a pretrained model
Traceback (most recent call last):
  File "demo.py", line 84, in <module>
    main()
  File "demo.py", line 55, in main
    download_model(DEFAULT_WEIGHTS)
  File "demo.py", line 34, in download_model
    '--create-dirs', '-o', fn])
  File "C:\Users\speed\AppData\Local\Programs\Python\Python35\Lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\speed\AppData\Local\Programs\Python\Python35\Lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\speed\AppData\Local\Programs\Python\Python35\Lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Could you please advise me the way to compile it, thanks.

**Comment by SJTUPanda** [comment]
Hi, I have the same error with you. Have you solved this problem?

**Comment by speed8928** [comment]
I lowered the Theano version 7.x then it worked.

**Comment by SJTUPanda** [comment]
Thanks! 
I use the Theano version 0.8.0 then it works.

**Comment by CloudChoSony** [comment]
I found another way to solve at [ValueError «You are trying to use the old GPU back-end» when importing keras](https://stackoverflow.com/questions/44765376/valueerror-you-are-trying-to-use-the-old-gpu-back-end-when-importing-keras)
According to cgl, please type in terminal "export THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float32"

**Comment by ShubhayanS** [comment]
> Thanks!
> I use the Theano version 0.8.0 then it works.

I am getting - AttributeError: ('This name is already taken', 'floatX')
