### ISSUE TITLE
Error after updating theano to 1.0.1 and updating padding variable to pad

### ISSUE THREAD

**Issue by prasad0896** [chrischoy/3D-R2N2#30]
Following is the error log that is generated. Kindly suggest. I am trying to execute the code on Windows 10 platform with anaconda 3.5

(base) D:\3D-R2N2-master>python demo.py p1.obj
Using cuDNN version 5110 on context None
Mapped name None to device cuda0: GeForce GTX 960M (0000:02:00.0)
Traceback (most recent call last):
  File "demo.py", line 84, in <module>
    main()
  File "demo.py", line 61, in main
    net = NetClass(compute_grad=False)  # instantiate a network
  File "D:\3D-R2N2-master\models\net.py", line 37, in __init__
    self.setup()
  File "D:\3D-R2N2-master\models\net.py", line 40, in setup
    self.network_definition()
  File "D:\3D-R2N2-master\models\res_gru_net.py", line 160, in network_definition
    dtype=theano.config.floatX)])
  File "D:\Anaconda3\lib\site-packages\theano\scan_module\scan.py", line 773, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "D:\3D-R2N2-master\models\res_gru_net.py", line 153, in recurrence
    return gru_out_.output, update_gate_.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 214, in set_output
    self._output = self._prev_layer.output + self._add_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 225, in set_output
    self._output = self._prev_layer.output * self._mult_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 657, in set_output
    self._output = sigmoid(self._prev_layer.output)
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 504, in set_output
    tensor.dot(self._fc_layer.output, self.Wx.val), self._output_shape)
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 637, in set_output
    self._input = self._prev_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 159, in set_output
    self._output = tensor.dot(self._prev_layer.output, self.W.val)
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 236, in set_output
    self._prev_layer.output.flatten(2)  # flatten from the second dim
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 351, in set_output
    input=self._prev_layer.output,
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 214, in set_output
    self._output = self._prev_layer.output + self._add_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 351, in set_output
    input=self._prev_layer.output,
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 214, in set_output
    self._output = self._prev_layer.output + self._add_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 319, in set_output
    padded_input = self._prev_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 351, in set_output
    input=self._prev_layer.output,
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 637, in set_output
    self._input = self._prev_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 313, in set_output
    self._prev_layer.output)
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 637, in set_output
    self._input = self._prev_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 313, in set_output
    self._prev_layer.output)
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 351, in set_output
    input=self._prev_layer.output,
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 214, in set_output
    self._output = self._prev_layer.output + self._add_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 319, in set_output
    padded_input = self._prev_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 351, in set_output
    input=self._prev_layer.output,
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 214, in set_output
    self._output = self._prev_layer.output + self._add_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 319, in set_output
    padded_input = self._prev_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 351, in set_output
    input=self._prev_layer.output,
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 637, in set_output
    self._input = self._prev_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 313, in set_output
    self._prev_layer.output)
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 637, in set_output
    self._input = self._prev_layer.output
  File "D:\3D-R2N2-master\lib\layers.py", line 129, in output
    self.set_output()
  File "D:\3D-R2N2-master\lib\layers.py", line 328, in set_output
    border_mode='valid')
  File "D:\Anaconda3\lib\site-packages\theano\tensor\nnet\__init__.py", line 169, in conv2d
    filter_dilation, num_groups, unshared)
  File "D:\Anaconda3\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 643, in conv2d
    unshared=unshared)
  File "D:\Anaconda3\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2465, in __init__
    unshared=unshared)
  File "D:\Anaconda3\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2314, in __init__
    unshared=unshared)
  File "D:\Anaconda3\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2103, in __init__
    self.imshp = tuple(imshp) if imshp else (None,) * (2 + convdim)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by kwcckw** [comment]
downgrade theano to 0.8.2 resolved this issue for me, but i'm still struggling to run the code in windows a lot complication issue
