### ISSUE TITLE
[question] How to generate higher resolution density (smaller voxel) models?

### ISSUE THREAD

**Issue by archenroot** [chrischoy/3D-R2N2#47]
I used this project in the past, now started playing again and being interested in generation of higher density of voxels from high resolution images, what parameters to touch?

Thank you very much for suggestions.

**Comment by archenroot** [comment]
Ok, I found confing.py file where I changed the W/H shape configuration and being able now to process higher resolutions.

So this error is gone:
```
     0.7411765 ]]]]]
None
Compiling testing function
Traceback (most recent call last):
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
ValueError: could not broadcast input array from shape (1,3,1368,1824) into shape (1,3,127,127)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
ValueError: could not broadcast input array from shape (1,3,1368,1824) into shape (1,3,127,127)
Apply node that caused the error: IncSubtensor{Set;::, ::, int64:int64:, int64:int64:}(TensorConstant{(1, 3, 133..33) of 0.0}, Rebroadcast{1}.0, Constant{3}, Constant{130}, Constant{3}, Constant{130})
Toposort index: 37
Inputs types: [TensorType(float32, (True, False, False, False)), TensorType(float32, (True, False, False, False)), Scalar(int64), Scalar(int64), Scalar(int64), Scalar(int64)]
Inputs shapes: [(1, 3, 133, 133), (1, 3, 1368, 1824), (), (), (), ()]
Inputs strides: [(212268, 70756, 532, 4), (29942784, 9980928, 7296, 4), (), (), (), ()]
Inputs values: ['not shown', 'not shown', 3, 130, 3, 130]
Outputs clients: [[CorrMM{valid, (1, 1), (1, 1), 1 False}(IncSubtensor{Set;::, ::, int64:int64:, int64:int64:}.0, Subtensor{::, ::, ::int64, ::int64}.0)]]

```

**Comment by archenroot** [comment]
But now after higher res I got:
```
Traceback (most recent call last):
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
ValueError: Shape mismatch: A.shape[1] != x.shape[0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
ValueError: Shape mismatch: A.shape[1] != x.shape[0]
Apply node that caused the error: CGemv{no_inplace}(InplaceDimShuffle{1}.0, TensorConstant{1.0}, InplaceDimShuffle{1,0}.0, Reshape{1}.0, TensorConstant{1.0})
Toposort index: 101
Inputs types: [TensorType(float32, vector), TensorType(float32, scalar), TensorType(float32, matrix), TensorType(float32, vector), TensorType(float32, scalar)]
Inputs shapes: [(1024,), (), (1024, 2304), (176640,), ()]
Inputs strides: [(4,), (), (4, 4096), (4,), ()]
Inputs values: ['not shown', array(1., dtype=float32), 'not shown', 'not shown', array(1., dtype=float32)]
Outputs clients: [[InplaceDimShuffle{x,0}(CGemv{no_inplace}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 84, in <module>
    main()
  File "demo.py", line 66, in main
    voxel_prediction, _ = solver.test_output(demo_imgs)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/lib/solver.py", line 235, in test_output
    results = self._test_output(x, y_val)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
ValueError: Shape mismatch: A.shape[1] != x.shape[0]
Apply node that caused the error: CGemv{no_inplace}(InplaceDimShuffle{1}.0, TensorConstant{1.0}, InplaceDimShuffle{1,0}.0, Reshape{1}.0, TensorConstant{1.0})
Toposort index: 101
Inputs types: [TensorType(float32, vector), TensorType(float32, scalar), TensorType(float32, matrix), TensorType(float32, vector), TensorType(float32, scalar)]
Inputs shapes: [(1024,), (), (1024, 2304), (176640,), ()]
Inputs strides: [(4,), (), (4, 4096), (4,), ()]
Inputs values: ['not shown', array(1., dtype=float32), 'not shown', 'not shown', array(1., dtype=float32)]
Outputs clients: [[InplaceDimShuffle{x,0}(CGemv{no_inplace}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: forall_inplace,cpu,scan_fn}(Shape_i{0}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, IncSubtensor{InplaceSet;:int64:}.0, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, 4D)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, InplaceDimShuffle{x,x,0,x,x}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0, Shape_i{4}.0, InplaceDimShuffle{x,x,0,x,x}.0, Shape_i{4}.0, Shape_i{3}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{2}.0, Reshape{4}.0, Shape_i{3}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{2}.0, Reshape{4}.0, InplaceDimShuffle{x,x,0,x,x}.0, Shape_i{4}.0, Shape_i{3}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{2}.0, Reshape{4}.0)
Toposort index: 230
Inputs types: [TensorType(int64, scalar), TensorType(float32, 5D), TensorType(float32, (False, True, False, False, False, False)), TensorType(float32, (False, True, False, False, False, False)), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, (True, True, False, True, True)), TensorType(float32, row), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(int64, scalar), TensorType(float32, (True, True, False, True, True)), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(float32, 4D), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(float32, 4D), TensorType(float32, (True, True, False, True, True)), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(float32, 4D)]
Inputs shapes: [(), (3, 1, 3, 1368, 1824), (2, 1, 4, 128, 4, 4), (3, 1, 4, 128, 4, 4), (96, 3, 7, 7), (96, 96, 3, 3), (128, 96, 1, 1), (128, 96, 3, 3), (128, 128, 3, 3), (256, 128, 1, 1), (256, 128, 3, 3), (256, 256, 3, 3), (256, 256, 3, 3), (256, 256, 3, 3), (256, 256, 1, 1), (256, 256, 3, 3), (256, 256, 3, 3), (256, 256, 3, 3), (256, 256, 3, 3), (2304, 1024), (1024, 8192), (1024, 8192), (1024, 8192), (1, 1, 128, 1, 1), (1, 1024), (1, 256, 1, 1), (1, 256, 1, 1), (1, 256, 1, 1), (1, 256, 1, 1), (1, 256, 1, 1), (1, 256, 1, 1), (1, 256, 1, 1), (1, 256, 1, 1), (1, 128, 1, 1), (1, 128, 1, 1), (1, 96, 1, 1), (1, 96, 1, 1), (1, 128, 1, 1), (1, 256, 1, 1), (1, 256, 1, 1), (), (1, 1, 128, 1, 1), (), (), (), (), (), (384, 128, 3, 3), (), (), (), (), (384, 128, 3, 3), (1, 1, 128, 1, 1), (), (), (), (), (), (384, 128, 3, 3)]
Inputs strides: [(), (29942784, 29942784, 9980928, 7296, 4), (32768, 32768, 8192, 64, 16, 4), (32768, 32768, 8192, 64, 16, 4), (588, 196, 28, 4), (3456, 36, 12, 4), (384, 4, 4, 4), (3456, 36, 12, 4), (4608, 36, 12, 4), (512, 4, 4, 4), (4608, 36, 12, 4), (9216, 36, 12, 4), (9216, 36, 12, 4), (9216, 36, 12, 4), (1024, 4, 4, 4), (9216, 36, 12, 4), (9216, 36, 12, 4), (9216, 36, 12, 4), (9216, 36, 12, 4), (4096, 4), (32768, 4), (32768, 4), (32768, 4), (512, 512, 4, 4, 4), (4096, 4), (1024, 4, 4, 4), (1024, 4, 4, 4), (1024, 4, 4, 4), (1024, 4, 4, 4), (1024, 4, 4, 4), (1024, 4, 4, 4), (1024, 4, 4, 4), (1024, 4, 4, 4), (512, 4, 4, 4), (512, 4, 4, 4), (384, 4, 4, 4), (384, 4, 4, 4), (512, 4, 4, 4), (1024, 4, 4, 4), (1024, 4, 4, 4), (), (512, 512, 4, 4, 4), (), (), (), (), (), (4608, 36, 12, 4), (), (), (), (), (4608, 36, 12, 4), (512, 512, 4, 4, 4), (), (), (), (), (), (4608, 36, 12, 4)]
Inputs values: [array(3), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', array(3), 'not shown', array(3), array(3), array(3), array(128), array(128), 'not shown', array(3), array(3), array(128), array(128), 'not shown', 'not shown', array(3), array(3), array(3), array(128), array(128), 'not shown']
Outputs clients: [[Subtensor{int64}(forall_inplace,cpu,scan_fn}.0, ScalarFromTensor.0)], [Subtensor{int64:int64:int8}(forall_inplace,cpu,scan_fn}.1, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
(venv) 

```

**Comment by archenroot** [comment]
This issue seems occurring when I change the initial resolution in config from 127/127 to any other value and the images are also following the same.
