### ISSUE TITLE
Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by archenroot** [chrischoy/3D-R2N2#48]
When trying to run demo I get:
```
 └─ ▶python demo.py prediction.obj
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType: None
/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/lib/layers.py:353: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  padding=self._padding)
/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/lib/layers.py:353: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
  padding=self._padding)
loading network parameters from output/ResidualGRUNet/default_model/weights.npy
Traceback (most recent call last):
  File "demo.py", line 84, in <module>
    main()
  File "demo.py", line 62, in main
    net.load(DEFAULT_WEIGHTS)                        # load downloaded weights
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/models/net.py", line 71, in load
    params_cpu_file = np.load(filename)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/zangetsu/proj/prometheus-core/demo/3D-R2N2/venv/lib/python3.6/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
(venv)
```

This error is realted to numpy > 1.16.1 (this version works)

**Comment by QJuse** [comment]
I get the same problem。when I set the allow_pickle = True(or install numpy = 1.16.1)， I solved it.
but  it occurs  another ERROR,  like this:
******************************************************
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhengqj/anaconda3/envs/py3-theano/lib/python3.6/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/zhengqj/anaconda3/envs/py3-theano/lib/python3.6/site-packages/numpy/lib/format.py", line 727, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated
************************************************************
anybody  has that problem?

**Comment by EmmaSRH** [comment]
conda install numpy=1.16.2
or
pip install numpy=1.16.2
