### ISSUE TITLE
 ValueError: Object arrays cannot be loaded when allow_pickle=False  

### ISSUE THREAD

**Issue by Longtime1994** [chrischoy/3D-R2N2#56]
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType: None
Y:\deep_learning\3D_R2N2\3D-R2N2-master\lib\layers.py:349: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  pooled_out = pool.pool_2d(
Y:\deep_learning\3D_R2N2\3D-R2N2-master\lib\layers.py:349: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
  pooled_out = pool.pool_2d(
loading network parameters from output/ResidualGRUNet/default_model/weights.npy
Traceback (most recent call last):
  File "Y:/deep_learning/3D_R2N2/3D-R2N2-master/demo.py", line 86, in <module>
    main()
  File "Y:/deep_learning/3D_R2N2/3D-R2N2-master/demo.py", line 64, in main
    net.load(DEFAULT_WEIGHTS)                        # load downloaded weights
  File "Y:\deep_learning\3D_R2N2\3D-R2N2-master\models\net.py", line 71, in load
    params_cpu_file = np.load(filename)
  File "Y:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 446, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "Y:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

Process finished with exit code 1

**Comment by TheRustlessSummer** [comment]
> ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
> NoneType: None
> Y:\deep_learning\3D_R2N2\3D-R2N2-master\lib\layers.py:349: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
> pooled_out = pool.pool_2d(
> Y:\deep_learning\3D_R2N2\3D-R2N2-master\lib\layers.py:349: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
> pooled_out = pool.pool_2d(
> loading network parameters from output/ResidualGRUNet/default_model/weights.npy
> Traceback (most recent call last):
> File "Y:/deep_learning/3D_R2N2/3D-R2N2-master/demo.py", line 86, in
> main()
> File "Y:/deep_learning/3D_R2N2/3D-R2N2-master/demo.py", line 64, in main
> net.load(DEFAULT_WEIGHTS) # load downloaded weights
> File "Y:\deep_learning\3D_R2N2\3D-R2N2-master\models\net.py", line 71, in load
> params_cpu_file = np.load(filename)
> File "Y:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 446, in load
> return format.read_array(fid, allow_pickle=allow_pickle,
> File "Y:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\format.py", line 692, in read_array
> raise ValueError("Object arrays cannot be loaded when "
> ValueError: Object arrays cannot be loaded when allow_pickle=False
> 
> Process finished with exit code 1

hello, I met the same question with you, have changed this question？

**Comment by SiyuanMengCN** [comment]
> > ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
> > NoneType: None
> > Y:\deep_learning\3D_R2N2\3D-R2N2-master\lib\layers.py:349: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
> > pooled_out = pool.pool_2d(
> > Y:\deep_learning\3D_R2N2\3D-R2N2-master\lib\layers.py:349: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
> > pooled_out = pool.pool_2d(
> > loading network parameters from output/ResidualGRUNet/default_model/weights.npy
> > Traceback (most recent call last):
> > File "Y:/deep_learning/3D_R2N2/3D-R2N2-master/demo.py", line 86, in
> > main()
> > File "Y:/deep_learning/3D_R2N2/3D-R2N2-master/demo.py", line 64, in main
> > net.load(DEFAULT_WEIGHTS) # load downloaded weights
> > File "Y:\deep_learning\3D_R2N2\3D-R2N2-master\models\net.py", line 71, in load
> > params_cpu_file = np.load(filename)
> > File "Y:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 446, in load
> > return format.read_array(fid, allow_pickle=allow_pickle,
> > File "Y:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\format.py", line 692, in read_array
> > raise ValueError("Object arrays cannot be loaded when "
> > ValueError: Object arrays cannot be loaded when allow_pickle=False
> > Process finished with exit code 1
> 
> hello, I met the same question with you, have changed this question？


Try to uninstall the numpy and insatll the previous version of numpy,such as numpy 1.16.1. I met the same question like you guys, this will help. Coz the new version of numpy  add some function which are different then this project.

**Comment by lhx0416** [comment]
> 

I also meet this question，your method did work,thanks.

**Comment by Nicola1921** [comment]
> Try to uninstall the numpy and insatll the previous version of numpy,such as numpy 1.16.1. I met the same question like you guys, this will help. Coz the new version of numpy add some function which are different then this project.

Thanks. A change of Numpy to Version 1.16.1 worked for me. 
Maybe this Version should be fixed in the ''requirements.txt'' or a code update.
