### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by GenaWang** [chrischoy/3D-R2N2#8]
@jgwak  @liujiaxing
Hi,I was trying to reproduce this experiment,and I follow the given instructions. My compilation environment is Python3.5.3. However,I meet the same problem that Liujiaxing met .
Could you give me some help or any suggestions? Thanks very much.

`Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -march=ivybridge -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-mwaitx -mno-clzero -mno-pku --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=3072 -mtune=ivybridge -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -I/home/wj/3D-R2N2/py3/include/python3.5m -I/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/gof -L/usr/lib -fvisibility=hidden -o /home/wj/.theano/compiledir_Linux-4.10--generic-x86_64-with-Ubuntu-17.04-zesty-x86_64-3.5.3-64/lazylinker_ext/lazylinker_ext.so /home/wj/.theano/compiledir_Linux-4.10--generic-x86_64-with-Ubuntu-17.04-zesty-x86_64-3.5.3-64/lazylinker_ext/mod.cpp -lpython3.5m
/home/wj/.theano/compiledir_Linux-4.10--generic-x86_64-with-Ubuntu-17.04-zesty-x86_64-3.5.3-64/lazylinker_ext/mod.cpp:1:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.

Traceback (most recent call last):
  File "/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 75, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 92, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    from models import load_model
  File "/home/wj/3D-R2N2/models/__init__.py", line 1, in <module>
    from models.gru_net import GRUNet
  File "/home/wj/3D-R2N2/models/gru_net.py", line 4, in <module>
    import theano
  File "/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/__init__.py", line 66, in <module>
    from theano.compile import (
  File "/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/compile/__init__.py", line 10, in <module>
    from theano.compile.function_module import *
  File "/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/compile/function_module.py", line 21, in <module>
    import theano.compile.mode
  File "/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/compile/mode.py", line 10, in <module>
    import theano.gof.vm
  File "/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/gof/vm.py", line 662, in <module>
    from . import lazylinker_c
  File "/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "/home/wj/3D-R2N2/py3/lib/python3.5/site-packages/theano/gof/cmodule.py", line 2316, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): /home/wj/.theano/compiledir_Linux-4.10--generic-x86_64-with-Ubuntu-17.04-zesty-x86_64-3.5.3-64/lazylinker_ext/mod.cpp:1:20: fatal error: Python.h: No such file or directory.  #include <Python.h>.  `

**Comment by chrischoy** [comment]
You need to install python3-dev.

Please install python3-dev by running

sudo apt-get install python3-dev

**Comment by GenaWang** [comment]
Thank you very much for your advice.The above problem has been solved. But there are new problems.

`ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    from models import load_model
  File "/home/wj/3D-R2N2/models/__init__.py", line 1, in <module>
    from models.gru_net import GRUNet
  File "/home/wj/3D-R2N2/models/gru_net.py", line 8, in <module>
    from lib.layers import TensorProductLayer, ConvLayer, PoolLayer, Unpool3DLayer, \
  File "/home/wj/3D-R2N2/lib/layers.py", line 8, in <module>
    from theano.tensor.signal import downsample
ImportError: cannot import name 'downsample'
`
I come from Tsinghua University from China. I am very interested in your experiment. So I am trying my best to reproduce this experiment,but often meet problems.
I am very sorry to brother you. Could you give me some help or any suggestions for this problem?

**Comment by archenroot** [comment]
https://github.com/Theano/Theano/issues/4337
